### ISSUE TITLE
how to parse __declspec attribute?

### ISSUE THREAD

**Issue by srxqds** [xoofx/CppAst.NET#41]
I found it can't pase __declspec attribute, how can I make it work?

**Comment by xoofx** [comment]
It depends. It is supported for some constructs (see [TestAttributes.cs](https://github.com/xoofx/CppAst.NET/blob/master/src/CppAst.Tests/TestAttributes.cs)), it might not be supported in some places.

Do you have a simple example where this is not working?

**Comment by srxqds** [comment]
@xoofx I test the code 
```c#
            string text = @"
#ifdef WIN32
#define EXPORT_API __declspec(dllexport)
#else
#define EXPORT_API __attribute__((visibility(""default"")))
#endif
EXPORT_API int function0();
int function1();
class EXPORT_API TestClass
{};

EXPORT_API class TestClass1
{};
";
```

the class attribute can't be parsed.

you can test it 
thank you.

**Comment by xoofx** [comment]
But the tests are checking exactly this and they are working, so you might have setup this differently. Could you post the exact code you are using for this, including the initialization of the parser?

**Comment by srxqds** [comment]
https://github.com/xoofx/CppAst.NET/blob/0b302770cf48de414aedf5ca7633b85b06fb6403/src/CppAst.Tests/TestFunctions.cs#L166 

you can replace the text with above, it can found the function has the attribute but class not.

**Comment by srxqds** [comment]
hi, @xoofx ,
I found if i write the attribute directly before class name, it can parsed,
```c#
string text = @"
#ifdef WIN32
#define EXPORT_API __declspec(dllexport)
#else
#define EXPORT_API __attribute__((visibility(""default"")))
#endif
EXPORT_API int function0();
int function1();
class EXPORT_API TestClass
{};

class __declspec(dllexport) TestClass1
{};
";
```

the **TestClass** have n't attribute, the **TestClass1** have attribute.

**Comment by srxqds** [comment]
may you fixed it or
how can I try fixed it?

thank you.

**Comment by xoofx** [comment]
By default, attributes are not parsed, are you sure you are passing `new CppParserOptions() { ParseAttributes = true }` as in the tests?

**Comment by srxqds** [comment]
> By default, attributes are not parsed, are you sure you are passing `new CppParserOptions() { ParseAttributes = true }` as in the tests?

yeah ,I set the ParseAttributes = true

**Comment by xoofx** [comment]
I believe that this particular attribute `__attribute__((visibility(""default"")))` is translated by clang to the property `.Visibility = Default`, not by an attached attribute.

**Comment by xoofx** [comment]
But it could be a bug, I don't know, don't have time to investigate this more.

**Comment by srxqds** [comment]
the detail of options and result:
![image](https://user-images.githubusercontent.com/5187024/97960289-24186d00-1dec-11eb-9299-3fba871626ad.png)

![image](https://user-images.githubusercontent.com/5187024/97960362-4c07d080-1dec-11eb-9721-ef1ed36dbf41.png)

**Comment by srxqds** [comment]
hi, @xoofx  I found that the https://github.com/xoofx/CppAst.NET/blob/0b302770cf48de414aedf5ca7633b85b06fb6403/src/CppAst/CppModelBuilder.cs#L2047 
**AttributeTokenizer** don't handle for CXCursorKind.CXCursor_ClassDecl kind ,so if it is a maco it will wrong.

may you help fixed it?

**Comment by xoofx** [comment]
> AttributeTokenizer don't handle for CXCursorKind.CXCursor_ClassDecl kind ,so if it is a maco it will wrong.
> may you help fixed it?

You maybe found the problem, so the fix might be easy. Could you try?

**Comment by srxqds** [comment]
but I could found where is the function get the macro extension.

**Comment by srxqds** [comment]
I think it is the clang or clangcsharp bug.

**Comment by srxqds** [comment]
hi, @xoofx 
It is becase if we define the attribute macro in the class. the libclang will directly parsed it as CXCursor_VisibilityAttr, CXCursor_DLLExport and CXCursor_DLLImport.

you can add below code into **VisitMember** function in CppModelBuilder.cs
```c#
case CXCursorKind.CXCursor_VisibilityAttr:
                    {
                        var containerContext = GetOrCreateDeclarationContainer(parent, data).Container;
                        var cppClass = containerContext as CppClass;
                        if (cppClass != null)
                        {
                            CppAttribute attribute = new CppAttribute("visibility");
                            attribute.Arguments = cursor.DisplayName.ToString();
                            cppClass.Attributes.Add(attribute);
                        }
                    }
                    break;
                case CXCursorKind.CXCursor_DLLImport:
                    {
                        var containerContext = GetOrCreateDeclarationContainer(parent, data).Container;
                        var cppClass = containerContext as CppClass;
                        if (cppClass != null)
                        {
                            cppClass.Attributes.Add(new CppAttribute("dllimport"));
                        }
                    }
                    break;
                case CXCursorKind.CXCursor_DLLExport:
                    {
                        var containerContext = GetOrCreateDeclarationContainer(parent, data).Container;
                        var cppClass = containerContext as CppClass;
                        if (cppClass != null)
                        {
                            cppClass.Attributes.Add(new CppAttribute("dllexport"));
                        }
                    }
                    break;
```
