### ISSUE TITLE
clang_EnumDecl_isScoped not found

### ISSUE THREAD

**Issue by danyhm** [xoofx/CppAst.NET#43]
Hi,

after a long day, I finally managed to supply the right arguments for the MingW64 8.1.0 Include folders and try to parse a header based on that.

however I think the Enum parser is broken (all other parsers work fine) , and when the parser sees an enum i get this exception in the visual studio 2019 debugger : 
```
System.EntryPointNotFoundException: 'Unable to find an entry point named 'clang_EnumDecl_isScoped' in DLL 'libclang'.'
in CppModelBuilder.cs line 1039:cppEnum.IsScoped = cursor.EnumDecl_IsScoped;
```

the same error is produced if I try the sample from the main page with an enum in it:
```
var compilation = CppParser.Parse(@"
enum MyEnum { MyEnum_0, MyEnum_1 };
void function0(int a, int b);
struct MyStruct { int field0; int field1;};
typedef MyStruct* MyStructPtr;
"
);
```

any ideas?

**Comment by xoofx** [comment]
Which version of `CppAst.CodeGen` are you using?

**Comment by danyhm** [comment]
I cloned the git repo, so I'm on the last commit of the master branch.

**Comment by xoofx** [comment]
Can't reproduce this on master + Windows. Are you running on Linux or MacOS maybe?

**Comment by xoofx** [comment]
Also inspecting the local libclang.dll file and I can see the symbol `clang_EnumDecl_isScoped` exported, so I believe that you have something weird on your setup as it doesn't seem to load the correct libclang.dll.

**Comment by danyhm** [comment]
I'm on windows. and you're right the function is exported. this is very strange. i think it has to be something related to .net platform maybe?

**Comment by xoofx** [comment]
Can you share your csproj?

**Comment by danyhm** [comment]
yes sure


[CppAst.NET-error.zip](https://github.com/xoofx/CppAst.NET/files/6000631/CppAst.NET-error.zip)

**Comment by xoofx** [comment]
Ok, so that's because you need to add this line to your csproj:

```xml
  <PropertyGroup>
    <!-- Workaround for issue https://github.com/microsoft/ClangSharp/issues/129 -->
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' AND '$(PackAsTool)' != 'true'">$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>
```

as it is done in the tests, otherwise it will copy the invalid DLL architecture.
Same if you consume the package.

**Comment by danyhm** [comment]
thanks ! that solved the problem !

**Comment by xoofx** [comment]
Great.
Related [Runtime packages not restoring properly? on ClangSharp](https://github.com/microsoft/ClangSharp/issues/118)  and [Improve handling of native packages on NuGet](https://github.com/NuGet/Home/issues/10571)
