### ISSUE TITLE
[Q] `'stddef.h' file not found` error

### ISSUE THREAD

**Issue by dehghani-mehdi** [xoofx/CppAst.NET#54]
I got 1 warning and 1 error as follow:

> warning: argument unused during compilation: '-fsyntax-only'

> error: 'stddef.h' file not found

Is this related to `CppAst` or should I install something else to fix the error?

**Comment by xoofx** [comment]
The error is because stdef.h is not in your include path. You might have to tweak it by passing relevant include directories for C/C++ std headers.

The warning is generated by clang, couldn't get rid of it but it's now filtered in 0.8.0+

**Comment by tuket** [comment]
Hello, I'm having the same problem.
I don't understand how to fix it.
Doesn't CppAst.NET come with the std headers?
Do I need to install them my self?
How do I setup the include path correctly?
The weird thing is that I asked two workmates to try my code and it works for them, and they didn't need to do anything special.
