### ISSUE TITLE
Should headerdoc comments be parsed when ParseComments is false?

### ISSUE THREAD

**Issue by waldnercharles** [xoofx/CppAst.NET#58]
I've noticed that headerdoc comments, (`/*! MyComment */`), get parsed even when `ParseComments` is set to false.
Is this expected behavior?

Test case to prove assertion:
```
ParseAssert(@"// This is a comment is ignored
int f0;

/*! This comment is parsed */
int f1;

/* This comment is ignored */
int f2;",
compilation => { ... },
new CppParserOptions { ParseComments = false });
```

**Comment by xoofx** [comment]
> Is this expected behavior?

I believe so. `ParseComments` is translated to `-fparse-all-comments` so that it will parse non-doxygen comments in addition to doxygen comments.

As explained in the doc: https://clang.llvm.org/docs/UsersManual.html#comment-parsing-options

> _Clang parses Doxygen and non-Doxygen style documentation comments and attaches them to the appropriate declaration nodes. **By default, it only parses Doxygen-style comments** and ignores ordinary comments starting with // and /*._

**Comment by waldnercharles** [comment]
Does it make sense to add support to ignore all comments, including doxygen comments?

**Comment by xoofx** [comment]
> Does it make sense to add support to ignore all comments, including doxygen comments?

I have never had the need for such a feature, because even if it parses the comment and I don't use them, it's not the end of the world. But, if you have a particular use case where it makes sense for it, feel free to make a PR.
