### ISSUE TITLE
no type named 'align_val_t' in namespace 'std'

### ISSUE THREAD

**Issue by nurbat** [xoofx/CppAst.NET#63]
![image](https://user-images.githubusercontent.com/5789051/176656598-df994680-9d42-4bd7-897d-e9557fadeed1.png)

**Comment by xoofx** [comment]
Too bad.

**Comment by nurbat** [comment]
I'm not happy at all, this std file is in this path, but cppAst doesn't want to take it. 
D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\include\vcruntime_new.h

```
SystemIncludeFolders =
    {
        @"D:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\include"
```

**Comment by xoofx** [comment]
> I'm not happy at all, this std file is in this path, but cppAst doesn't want to take it.

Because you think I was happy about the way you reported that issue?

Just to be clear, If you have a bug, you will have to investigate it yourself. I won't do that for you just because you are not happy. It is an OSS project here and I'm not your minion.
