### ISSUE TITLE
how to get field position of anonymous struct/union?

### ISSUE THREAD

**Issue by TechInterMezzo** [xoofx/CppAst.NET#65]
```
struct operator 
{
    int type;
    union 
    {
        int intNum;
        float floatNum;
        double doubleNum;
    };
};
```

Taking this C snippet as an example. Is it possible to find out if the union is located after or before the "type" field?
The union is not listed as a field, which is understandable. But if I use the "Children" method of the parent struct, the union is listed before the "type" field.

**Comment by xoofx** [comment]
Thanks, indeed, I actually went through a similar issue just recently! 😅  

I pushed a fix 0894624, should be available in upcoming `0.9.2+`
