### ISSUE TITLE
How to get information about dllexport on parse result

### ISSUE THREAD

**Issue by anchurcn** [xoofx/CppAst.NET#71]

**Comment by anchurcn** [comment]
I want to find all functions marked with __declspec(dllexport)

**Comment by xoofx** [comment]
[here](https://github.com/xoofx/CppAst.NET/blob/d0d3a1ffd8cbdd035bf797d477bfd76ed7773f03/src/CppAst.Tests/TestAttributes.cs#L13-L63)?

**Comment by anchurcn** [comment]
Thanks, I see.
