### ISSUE TITLE
Memory Leak on call CppParser.Parse() ? 

### ISSUE THREAD

**Issue by CuriousTama** [xoofx/CppAst.NET#94]
I there, while working on a project that call parse multiple time before closing, I spotted the Process Memory only going up, after some investigation I have done this test: 

https://github.com/xoofx/CppAst.NET/assets/52009799/279bf25e-e614-4426-915e-af75f9bb5790

Quite a simple test, using the example provided in the README file, I just surrounded it in a while loop to make multiple calls before killing the process.

Here we see the leak is only some MB, but on "true files" it's a way bigger leak.

The test was done with nugget v0.15.0 and v0.14.0.

I don't think my usage of it is the problem, but let me know if I that the case.

**Comment by xoofx** [comment]
> Quite a simple test, using the example provided in the README file, I just surrounded it in a while loop to make multiple calls before killing the process.

It is definitely possible, as this library as been mainly developed to be used from an executable and to process C++ headers just once, so there was little care to check if all native memory allocated has been released. Hopefully, it shouldn't be much work to fix this. PR welcome.

**Comment by CuriousTama** [comment]
Hi again, FYI, I'm on it, Digging goes wonderfully, I will try to have a fix~

**Comment by CuriousTama** [comment]
Should be fixed with #99 and available with `0.17.0`.
Hopefully, I did not miss any edge cases.
